enabled: true
root_page: 					                        # optional: set root page of documentation
top_level_version: false                            # Use versions for top level navigation
google_analytics_code:                              # Enter your `UA-XXXXXXXX-X` code here
home_url:  http://training.maas.lab
github:
    position: top                                   # top | bottom | off
    icon: top                                       # FontAwesome icon
    tree: 
default_taxonomy_category: docs

streams:
 schemes:
   theme:
     type: ReadOnlyStream
     prefixes:
       '':
       - 'user://themes/labs'
       - 'user://themes/quark'